---
- name: Update repositories cache
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
  when: ansible_pkg_mgr == "apt"

- name: Install "nginx" package
  apt:
    name: nginx-full
  when: ansible_pkg_mgr == "apt"

- name: Set nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  register: nginx_reload

- name: Place template pam nginx file
  template:
    src: templates/pam_service_file.j2
    dest: "/etc/pam.d/{{ nginx_pam_service_name | mandatory }}"
  when: nginx_pam_rules is defined

- name: Enable and start nginx
  systemd:
    name: nginx.service
    state: reloaded
    enabled: True
  when: ansible_service_mgr == "systemd" and nginx_reload.changed
